name: Secure Dump Secrets

on:
  workflow_dispatch:

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Encrypt and Dump Secrets
        run: |
          # Gabungkan semua secrets ke dalam format properties
          SECRETS_DATA=$(cat <<EOF
          BYPASS_PASSWORD=${{ secrets.BYPASS_PASSWORD }}
          CLONER_SIGNATURE=${{ secrets.CLONER_SIGNATURE }}
          FALLBACK_RELEASE_URL=${{ secrets.FALLBACK_RELEASE_URL }}
          FBOX_OAUTH_CLIENT_ID=${{ secrets.FBOX_OAUTH_CLIENT_ID }}
          FBOX_OAUTH_CLIENT_SECRET=${{ secrets.FBOX_OAUTH_CLIENT_SECRET }}
          GIST_ID=${{ secrets.GIST_ID }}
          GIST_TOKEN=${{ secrets.GIST_TOKEN }}
          MELOLO_API_PATH=${{ secrets.MELOLO_API_PATH }}
          MELOLO_URL=${{ secrets.MELOLO_URL }}
          MOVIEBOX_SECRET_KEY_ALT=${{ secrets.MOVIEBOX_SECRET_KEY_ALT }}
          MOVIEBOX_SECRET_KEY_DEFAULT=${{ secrets.MOVIEBOX_SECRET_KEY_DEFAULT }}
          RBTV_AES_IV=${{ secrets.RBTV_AES_IV }}
          RBTV_AES_KEY=${{ secrets.RBTV_AES_KEY }}
          RBTV_API_HOST=${{ secrets.RBTV_API_HOST }}
          RBTV_FALLBACK_URL=${{ secrets.RBTV_FALLBACK_URL }}
          RBTV_GIST_URL=${{ secrets.RBTV_GIST_URL }}
          RBTV_MAIN_URL=${{ secrets.RBTV_MAIN_URL }}
          RBTV_PATH_BS=${{ secrets.RBTV_PATH_BS }}
          RBTV_PATH_DETAIL=${{ secrets.RBTV_PATH_DETAIL }}
          RBTV_PATH_LIVE=${{ secrets.RBTV_PATH_LIVE }}
          RBTV_PATH_STREAM_DETAIL=${{ secrets.RBTV_PATH_STREAM_DETAIL }}
          RBTV_SITE_URL=${{ secrets.RBTV_SITE_URL }}
          RBTV_USER_AGENT=${{ secrets.RBTV_USER_AGENT }}
          SHORTMAX_KEY=${{ secrets.SHORTMAX_KEY }}
          SHORTMAX_URL=${{ secrets.SHORTMAX_URL }}
          UPDATE_JSON_URL=${{ secrets.UPDATE_JSON_URL }}
          XR3EDTV_WORKER_TOKEN=${{ secrets.XR3EDTV_WORKER_TOKEN }}
          XR3EDTV_WORKER_URL=${{ secrets.XR3EDTV_WORKER_URL }}
          XR3EV_API_URL=${{ secrets.XR3EV_API_URL }}
          XR3EV_MAIN_URL=${{ secrets.XR3EV_MAIN_URL }}
          XR3EV_PASSWORD=${{ secrets.XR3EV_PASSWORD }}
          XR3EV_PLAYER_URL=${{ secrets.XR3EV_PLAYER_URL }}
          XR3EV_SALT=${{ secrets.XR3EV_SALT }}
          XR3EV_STREAM_URL=${{ secrets.XR3EV_STREAM_URL }}
          XSTREAM_TMDB_API=${{ secrets.XSTREAM_TMDB_API }}
          EOF
          )
          
          echo "=== ENCRYPTED BLOCK START ==="
          echo "$SECRETS_DATA" | gpg --symmetric --batch --passphrase "xr3ed_temp_passphrase_2026_secure" --armor
          echo "=== ENCRYPTED BLOCK END ==="
